In [1]:
#Importing libraries

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import metrics
%matplotlib inline

In [2]:
#Load your dataset into a pandas Function

def load_dataset():
    global fetalHealth #When you declare df to be global, it can work outside function
    #Replace 'file_path' with the actual path to your dataset file

    fetalHealth =pd.read_csv('fetal_health.csv')
    return fetalHealth
load_dataset()

baseline value  accelerations  fetal_movement  uterine_contractions  \
0              120.0          0.000           0.000                 0.000   
1              132.0          0.006           0.000                 0.006   
2              133.0          0.003           0.000                 0.008   
3              134.0          0.003           0.000                 0.008   
4              132.0          0.007           0.000                 0.008   
...              ...            ...             ...                   ...   
2121           140.0          0.000           0.000                 0.007   
2122           140.0          0.001           0.000                 0.007   
2123           140.0          0.001           0.000                 0.007   
2124           140.0          0.001           0.000                 0.006   
2125           142.0          0.002           0.002                 0.008   

      light_decelerations  severe_decelerations  prolongued_decelerations  \
0                   0.000                   0.0                       0.0   
1                   0.003                   0.0                       0.0   
2                   0.003                   0.0                       0.0   
3                   0.003                   0.0                       0.0   
4                   0.000                   0.0                       0.0   
...                   ...                   ...                       ...   
2121                0.000                   0.0                       0.0   
2122                0.000                   0.0                       0.0   
2123                0.000                   0.0                       0.0   
2124                0.000                   0.0                       0.0   
2125                0.000                   0.0                       0.0   

      abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                                73.0                                   0.5   
1                                17.0                                   2.1   
2                                16.0                                   2.1   
3                                16.0                                   2.4   
4                                16.0                                   2.4   
...                               ...                                   ...   
2121                             79.0                                   0.2   
2122                             78.0                                   0.4   
2123                             79.0                                   0.4   
2124                             78.0                                   0.4   
2125                             74.0                                   0.4   

      percentage_of_time_with_abnormal_long_term_variability  ...  \
0                                                  43.0       ...   
1                                                   0.0       ...   
2                                                   0.0       ...   
3                                                   0.0       ...   
4                                                   0.0       ...   
...                                                 ...       ...   
2121                                               25.0       ...   
2122                                               22.0       ...   
2123                                               20.0       ...   
2124                                               27.0       ...   
2125                                               36.0       ...   

      histogram_min  histogram_max  histogram_number_of_peaks  \
0              62.0          126.0                        2.0   
1              68.0          198.0                        6.0   
2              68.0          198.0                        5.0   
3              53.0          170.0                       11.0   
4              53.0          170.0                   

In [3]:
#To get the column titles
fetalHealth.columns

Index(['baseline value', 'accelerations', 'fetal_movement',
       'uterine_contractions', 'light_decelerations', 'severe_decelerations',
       'prolongued_decelerations', 'abnormal_short_term_variability',
       'mean_value_of_short_term_variability',
       'percentage_of_time_with_abnormal_long_term_variability',
       'mean_value_of_long_term_variability', 'histogram_width',
       'histogram_min', 'histogram_max', 'histogram_number_of_peaks',
       'histogram_number_of_zeroes', 'histogram_mode', 'histogram_mean',
       'histogram_median', 'histogram_variance', 'histogram_tendency',
       'fetal_health'],
      dtype='object')

In [4]:
#To get the dimensions of the dataset

fetalHealth.shape

(2126, 22)

In [5]:
#Checking out for missing values or entries
fetalHealth.isnull().sum()

baseline value                                            0
accelerations                                             0
fetal_movement                                            0
uterine_contractions                                      0
light_decelerations                                       0
severe_decelerations                                      0
prolongued_decelerations                                  0
abnormal_short_term_variability                           0
mean_value_of_short_term_variability                      0
percentage_of_time_with_abnormal_long_term_variability    0
mean_value_of_long_term_variability                       0
histogram_width                                           0
histogram_min                                             0
histogram_max                                             0
histogram_number_of_peaks                                 0
histogram_number_of_zeroes                                0
histogram_mode                          

In [6]:
#To view the dimensions of the dataset ie the rows and columns
fetalHealth.shape

(2126, 22)

In [7]:
#To get the aggregates function

fetalHealth.describe()

baseline value  accelerations  fetal_movement  uterine_contractions  \
count     2126.000000    2126.000000     2126.000000           2126.000000   
mean       133.303857       0.003178        0.009481              0.004366   
std          9.840844       0.003866        0.046666              0.002946   
min        106.000000       0.000000        0.000000              0.000000   
25%        126.000000       0.000000        0.000000              0.002000   
50%        133.000000       0.002000        0.000000              0.004000   
75%        140.000000       0.006000        0.003000              0.007000   
max        160.000000       0.019000        0.481000              0.015000   

       light_decelerations  severe_decelerations  prolongued_decelerations  \
count          2126.000000           2126.000000               2126.000000   
mean              0.001889              0.000003                  0.000159   
std               0.002960              0.000057                  0.000590   
min               0.000000              0.000000                  0.000000   
25%               0.000000              0.000000                  0.000000   
50%               0.000000              0.000000                  0.000000   
75%               0.003000              0.000000                  0.000000   
max               0.015000              0.001000                  0.005000   

       abnormal_short_term_variability  mean_value_of_short_term_variability  \
count                      2126.000000                           2126.000000   
mean                         46.990122                              1.332785   
std                          17.192814                              0.883241   
min                          12.000000                              0.200000   
25%                          32.000000                              0.700000   
50%                          49.000000                              1.200000   
75%                          61.000000                              1.700000   
max                          87.000000                              7.000000   

       percentage_of_time_with_abnormal_long_term_variability  ...  \
count                                         2126.00000       ...   
mean                                             9.84666       ...   
std                                             18.39688       ...   
min                                              0.00000       ...   
25%                                              0.00000       ...   
50%                                              0.00000       ...   
75%                                             11.00000       ...   
max                                             91.00000       ...   

       histogram_min  histogram_max  histogram_number_of_peaks  \
count    2126.000000    2126.000000                2126.000000   
mean       93.579492     164.025400                   4.068203   
std        29.560212      17.944183                   2.949386   
min        50.000000     122.000000                   0.000000   
25%        67.000000     152.000000                   2.000000   
50%        93.000000     162.000000                   3.000000   
75%       120.000000     174.000000                   6.000000   
max       159.000000     238.000000                  18.000000   

       histogram_number_of_zeroes  histogram_mode  histogram_mean  \
count                 2126.000000     2126.000000     2126.000000   
mean                     0.323612      137.452023      134.610536   
std                      0.706059       16.381289       15.593596   
min                      0.000000       60.000000       73.000000   
25%                      0.000000      129.000000      125.000000   
50%                      0.000000      139.000000      136.000000   
75%                      0.000000      148.000000      145.000000   
max                     10.000000      187.000000      182.000000   

       histogram_median  histogr

In [8]:
#To get the entries of fetalhealth column that are 1.0

fetalHealth[fetalHealth['fetal_health']==1.0]

baseline value  accelerations  fetal_movement  uterine_contractions  \
1              132.0          0.006           0.000                 0.006   
2              133.0          0.003           0.000                 0.008   
3              134.0          0.003           0.000                 0.008   
4              132.0          0.007           0.000                 0.008   
12             131.0          0.005           0.072                 0.008   
...              ...            ...             ...                   ...   
2117           140.0          0.000           0.000                 0.008   
2118           140.0          0.000           0.000                 0.006   
2119           140.0          0.000           0.000                 0.007   
2120           140.0          0.000           0.000                 0.005   
2125           142.0          0.002           0.002                 0.008   

      light_decelerations  severe_decelerations  prolongued_decelerations  \
1                   0.003                   0.0                       0.0   
2                   0.003                   0.0                       0.0   
3                   0.003                   0.0                       0.0   
4                   0.000                   0.0                       0.0   
12                  0.003                   0.0                       0.0   
...                   ...                   ...                       ...   
2117                0.000                   0.0                       0.0   
2118                0.001                   0.0                       0.0   
2119                0.001                   0.0                       0.0   
2120                0.001                   0.0                       0.0   
2125                0.000                   0.0                       0.0   

      abnormal_short_term_variability  mean_value_of_short_term_variability  \
1                                17.0                                   2.1   
2                                16.0                                   2.1   
3                                16.0                                   2.4   
4                                16.0                                   2.4   
12                               28.0                                   1.4   
...                               ...                                   ...   
2117                             79.0                                   0.3   
2118                             79.0                                   0.5   
2119                             79.0                                   0.6   
2120                             77.0                                   0.7   
2125                             74.0                                   0.4   

      percentage_of_time_with_abnormal_long_term_variability  ...  \
1                                                   0.0       ...   
2                                                   0.0       ...   
3                                                   0.0       ...   
4                                                   0.0       ...   
12                                                  0.0       ...   
...                                                 ...       ...   
2117                                               20.0       ...   
2118                                               26.0       ...   
2119                                               27.0       ...   
2120                                               17.0       ...   
2125                                               36.0       ...   

      histogram_min  histogram_max  histogram_number_of_peaks  \
1              68.0          198.0                        6.0   
2              68.0          198.0                        5.0   
3              53.0          170.0                       11.0   
4              53.0          170.0                        9.0   
12             88.0          154.0                   

In [9]:
#To count the number of fetal health column that are 2.0

count = 0

for i in fetalHealth['fetal_health']:
    if i ==2.0:
        count+=1
print(count)

295


In [10]:
#correlation matrix
corrmat= fetalHealth.corr()
plt.figure(figsize=(15,15))  

cmap = sns.diverging_palette(250, 10, s=80, l=55, n=9, as_cmap=True)

sns.heatmap(corrmat,annot=True, cmap=cmap, center=0)

<Axes: >

In [11]:
#Divide the data into features and label
#for the features 
X = fetalHealth.drop('fetal_health', axis=1)
#for the label
y = fetalHealth['fetal_health']

In [12]:
#Spliting the data
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.2, random_state=42)

In [27]:
#Since it is a multiclass category, it is important to use different algorithms for a balnced performance

def decision_tree_regressor(): 
    global DTR_model
    global DTR_predict
    DTR_model = DecisionTreeRegressor()
    DTR_model.fit(Xtrain, ytrain)
    DTR_predict = DTR_model.predict(Xtest)
    DTR_model = DTR_model.score(Xtrain, ytrain)
    return DTR_predict
decision_tree_regressor()

array([1., 1., 1., 1., 1., 3., 1., 3., 2., 2., 1., 3., 1., 1., 1., 1., 1.,
       1., 2., 1., 1., 1., 3., 1., 1., 3., 3., 2., 1., 1., 1., 1., 1., 2.,
       1., 1., 1., 3., 2., 2., 1., 2., 1., 1., 1., 1., 1., 3., 1., 1., 1.,
       1., 2., 2., 2., 1., 1., 1., 2., 1., 2., 1., 1., 1., 1., 1., 2., 1.,
       1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 2., 1.,
       1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 3., 2., 1., 2., 1.,
       1., 2., 1., 2., 1., 1., 3., 1., 2., 1., 1., 2., 1., 3., 1., 1., 2.,
       1., 1., 2., 1., 1., 3., 3., 3., 1., 1., 1., 3., 1., 1., 1., 1., 1.,
       1., 3., 1., 2., 2., 2., 1., 1., 3., 1., 1., 1., 1., 2., 1., 1., 2.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 2., 1., 2., 1.,
       1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 3., 2., 1., 1., 1., 2., 1., 2., 1., 1., 1., 2., 1., 1., 1., 2.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       2., 1., 1., 1., 1.

In [30]:
DTR_score = DTR_model
DTR_score

1.0

In [14]:
#An algorithm called Random Forest Regressorc

def random_forest_regressor():
    global RFC_model
    global RFC_predict
    RFC_model = RandomForestRegressor()
    RFC_model.fit(Xtrain, ytrain)
    RFC_predict = RFC_model.predict(Xtest)
    return RFC_predict
random_forest_regressor()

array([1.  , 1.  , 1.04, 1.  , 1.  , 2.98, 1.  , 2.99, 1.83, 1.99, 1.  ,
       2.88, 1.2 , 1.  , 1.  , 1.3 , 1.93, 1.  , 1.66, 1.  , 1.  , 1.  ,
       2.97, 1.  , 1.14, 3.  , 3.  , 1.4 , 1.  , 1.  , 1.2 , 1.  , 1.  ,
       1.63, 1.  , 1.  , 1.  , 3.  , 2.  , 1.98, 1.  , 2.  , 1.  , 1.  ,
       1.  , 1.59, 1.  , 2.94, 1.  , 1.  , 1.  , 1.02, 1.91, 1.94, 2.  ,
       1.  , 1.01, 1.  , 1.88, 1.03, 1.62, 1.  , 1.08, 1.  , 1.01, 1.  ,
       1.92, 1.  , 1.01, 1.01, 1.  , 1.  , 1.  , 1.06, 1.  , 1.85, 1.  ,
       1.06, 1.  , 1.78, 1.01, 1.  , 1.01, 1.56, 1.06, 1.  , 1.  , 1.57,
       1.  , 1.66, 1.  , 1.01, 1.  , 1.04, 1.97, 1.  , 1.  , 2.66, 1.89,
       1.  , 2.03, 1.  , 1.  , 1.14, 1.  , 2.  , 1.16, 1.01, 2.99, 1.12,
       1.97, 1.76, 1.  , 1.98, 1.02, 2.99, 1.  , 1.  , 2.  , 1.07, 1.06,
       1.8 , 1.  , 1.  , 2.88, 2.96, 3.  , 1.  , 1.08, 1.  , 2.84, 1.  ,
       1.  , 1.01, 1.28, 1.04, 1.35, 1.22, 1.33, 1.99, 1.83, 1.47, 1.94,
       1.  , 2.74, 1.02, 1.  , 1.05, 1.  , 1.2 , 1.

In [15]:
RFC_score = RFC_model.score(Xtrain, ytrain)
RFC_score

0.978040172834531

In [16]:
#This is another algorithm called Gradient Boosting Regressor

def gradient_boosting_regressor():
    global GBR_model
    global GBR_predict
    GBR_model = GradientBoostingRegressor()
    GBR_model.fit(Xtrain, ytrain)
    GBR_predict = GBR_model.predict(Xtest)
    return GBR_predict
gradient_boosting_regressor()

array([1.00894265, 1.05455228, 1.07944533, 0.97227603, 1.15215057,
       3.08607546, 1.03163723, 2.96721285, 1.68695903, 1.99766527,
       0.97422446, 3.00763024, 1.10046921, 0.94811797, 1.01355407,
       1.36765267, 1.8488708 , 0.98962938, 1.54209137, 1.04848944,
       1.05893495, 0.96795589, 3.06829692, 1.00925931, 1.0733211 ,
       2.96176677, 2.94970164, 1.30256673, 0.98038825, 0.97703896,
       1.36751157, 0.94981203, 0.98512853, 1.42779836, 1.03647929,
       0.99677672, 1.01254517, 3.12177839, 2.03379046, 1.8987612 ,
       0.97679694, 2.15928672, 0.97011461, 0.97769419, 0.97247685,
       1.25796355, 0.98961935, 3.02704471, 0.97382586, 1.02345496,
       1.02995157, 1.01460609, 1.94195345, 1.89433142, 2.09180058,
       0.98263763, 1.07098024, 1.02979455, 1.62423659, 1.11099147,
       1.76478034, 1.03594727, 1.13377167, 0.97206303, 1.03272138,
       1.02809319, 1.93520028, 1.01457347, 1.03611635, 1.05035878,
       0.96217453, 1.00814754, 1.04313334, 1.07781029, 1.00151

In [17]:
GBR_score = GBR_model.score(Xtrain, ytrain)
GBR_score

0.9224674615075678

In [18]:
def support_vector_regressor():
    global SVR_model
    global SVR_predict
    SVR_model = SVR()
    SVR_model.fit(Xtrain, ytrain)
    SVR_predict = SVR_model.predict(Xtest)
    return SVR_predict
support_vector_regressor()

array([0.96817015, 1.17157116, 1.10391094, 0.87219832, 1.25338551,
       2.62472372, 1.02587303, 2.53224455, 1.1153395 , 1.42827947,
       1.06157042, 1.93495373, 1.23498406, 0.9425374 , 0.96025925,
       1.24093797, 1.2528823 , 1.07930358, 1.44934326, 0.91963743,
       1.10742788, 0.91944439, 2.33140289, 1.02228986, 1.08152072,
       2.48543483, 1.81452507, 1.82290442, 0.95031824, 1.03768942,
       1.29213846, 1.1001601 , 1.04379675, 1.798627  , 1.17162585,
       0.96724795, 1.09957247, 3.41471775, 1.90408834, 2.10460305,
       0.92698251, 1.8837648 , 0.87826285, 1.00828966, 0.99539603,
       1.66838865, 1.13966227, 1.92465404, 0.89846973, 0.98097958,
       0.94076391, 0.95490806, 1.98443373, 1.54866303, 1.84773774,
       1.05667592, 1.00602372, 0.96198132, 1.29176187, 1.08205667,
       1.5026704 , 1.42733358, 1.07386794, 0.8897087 , 1.50925495,
       0.99568499, 1.47666128, 0.96271441, 0.99898378, 1.19290191,
       1.05966575, 0.92768334, 1.16457688, 1.42423214, 0.95141

In [19]:
SVR_model.score(Xtrain, ytrain)

0.5342938228330033

In [20]:
def neural_network_regressor():
    global NNR_model
    global NNR_predict
    NNR_model = MLPRegressor()
    NNR_model.fit(Xtrain, ytrain)
    NNR_predict = NNR_model.predict(Xtest)
    return NNR_predict
neural_network_regressor()

array([1.35726947, 1.74128943, 1.26028019, 0.91505034, 1.28169193,
       2.9239046 , 1.15106348, 2.92911908, 1.3698669 , 1.72300469,
       1.40691591, 2.02759458, 1.38370704, 0.87508515, 1.17715923,
       1.4166408 , 3.39233495, 1.26328557, 1.69455397, 1.16308436,
       1.36274357, 1.02760628, 2.56057792, 1.28870197, 1.33540252,
       2.862106  , 2.22102072, 1.55585975, 1.01597072, 1.22204689,
       3.23781805, 1.04745669, 1.23276971, 1.98326355, 1.37540003,
       1.13709714, 1.40837071, 3.73209435, 1.96210439, 2.20069235,
       1.10546643, 2.00995944, 0.9066822 , 1.19080294, 1.2113021 ,
       1.67025872, 0.82671335, 1.92605611, 1.0151345 , 2.04053084,
       1.27893158, 1.26828506, 1.82990077, 1.67452624, 1.9327117 ,
       1.32283633, 1.00517711, 1.24161013, 2.09853067, 1.26017644,
       1.6241266 , 1.52855395, 1.20311146, 0.80326136, 1.57777785,
       1.17655129, 1.78508768, 1.18592445, 1.16212114, 1.17179239,
       1.20527378, 1.09700706, 1.08904188, 1.43256265, 1.09091

In [21]:
NNR_score = NNR_model.score(Xtrain, ytrain)
NNR_score

0.5032304707900266

In [22]:
GBR_predict

array([1.00894265, 1.05455228, 1.07944533, 0.97227603, 1.15215057,
       3.08607546, 1.03163723, 2.96721285, 1.68695903, 1.99766527,
       0.97422446, 3.00763024, 1.10046921, 0.94811797, 1.01355407,
       1.36765267, 1.8488708 , 0.98962938, 1.54209137, 1.04848944,
       1.05893495, 0.96795589, 3.06829692, 1.00925931, 1.0733211 ,
       2.96176677, 2.94970164, 1.30256673, 0.98038825, 0.97703896,
       1.36751157, 0.94981203, 0.98512853, 1.42779836, 1.03647929,
       0.99677672, 1.01254517, 3.12177839, 2.03379046, 1.8987612 ,
       0.97679694, 2.15928672, 0.97011461, 0.97769419, 0.97247685,
       1.25796355, 0.98961935, 3.02704471, 0.97382586, 1.02345496,
       1.02995157, 1.01460609, 1.94195345, 1.89433142, 2.09180058,
       0.98263763, 1.07098024, 1.02979455, 1.62423659, 1.11099147,
       1.76478034, 1.03594727, 1.13377167, 0.97206303, 1.03272138,
       1.02809319, 1.93520028, 1.01457347, 1.03611635, 1.05035878,
       0.96217453, 1.00814754, 1.04313334, 1.07781029, 1.00151

In [23]:
def support_vector_regressor():
    global SVR_model
    global SVR_predict
    SVR_model = SVR()
    SVR_model.fit(Xtrain, ytrain)
    SVR_predict = SVR_model.predict(Xtest)
    SVR_model = SVR_model.score(Xtrain, ytrain)
    return round((SVR_model),3)
support_vector_regressor()

0.534

In [24]:
SVR_predict

array([0.96817015, 1.17157116, 1.10391094, 0.87219832, 1.25338551,
       2.62472372, 1.02587303, 2.53224455, 1.1153395 , 1.42827947,
       1.06157042, 1.93495373, 1.23498406, 0.9425374 , 0.96025925,
       1.24093797, 1.2528823 , 1.07930358, 1.44934326, 0.91963743,
       1.10742788, 0.91944439, 2.33140289, 1.02228986, 1.08152072,
       2.48543483, 1.81452507, 1.82290442, 0.95031824, 1.03768942,
       1.29213846, 1.1001601 , 1.04379675, 1.798627  , 1.17162585,
       0.96724795, 1.09957247, 3.41471775, 1.90408834, 2.10460305,
       0.92698251, 1.8837648 , 0.87826285, 1.00828966, 0.99539603,
       1.66838865, 1.13966227, 1.92465404, 0.89846973, 0.98097958,
       0.94076391, 0.95490806, 1.98443373, 1.54866303, 1.84773774,
       1.05667592, 1.00602372, 0.96198132, 1.29176187, 1.08205667,
       1.5026704 , 1.42733358, 1.07386794, 0.8897087 , 1.50925495,
       0.99568499, 1.47666128, 0.96271441, 0.99898378, 1.19290191,
       1.05966575, 0.92768334, 1.16457688, 1.42423214, 0.95141

In [32]:
#To view all the performance of all the algorithm which indicates that Decision Tree Regressor does predicted well

print(f'''
DecisionTreeRegressor: {DTR_model}, 
SupportVectorRegressor: {SVR_model},
NeuralNetworkRegressor: {NNR_score},
GradientBoostingRegressor:{GBR_score}''')


DecisionTreeRegressor: 1.0, 
SupportVectorRegressor: 0.5342938228330033,
NeuralNetworkRegressor: 0.5032304707900266,
GradientBoostingRegressor:0.9224674615075678


In [ ]:

def evaluate_model():
    global rmse
    global mse
    global r2
    global mae
    rmse = np.sqrt(mean_squared_error(ytest, DTR_predict)) #evaluating by root mean square error
    mse =  mean_squared_error(ytest, DTR_predict) #evaluating by mean square error
    r2 = r2_score(ytest, DTR_predict) #evaluating by r_squared
    mae = metrics.mean_absolute_error(ytest, DTR_predict)
    return ((rmse, mse, r2, mae))
evaluate_model()

In [ ]:
#let us import three essential evaluation metrics from scikit-learn's metrics module, which are commonly used in classification machine learning.
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
#let us print the classification report for the ytest (the testing target data) and the Xpreds (the prediction of the model xtest (testing 
#feature data)
#this classification report gives a summary of the precision, recall, f1-score and support 
print(classification_report(ytest, DTR_predict))